### PR TITLE
Add Dependabot configuration

### PR DESCRIPTION
**Pull request by WadeBarnes**
- Configure Dependabot to automatically maintain dependencies for GitHub Actions.
  - Check for updates once a week.
  - Group all updates into a single PR.

### CODE REVIEW

**Comment by TimoGlastra** [comment]
The dependabot file does not conform to prettier formatting rules.

I'll run prettier on the file and update the PR (or you can run prettier locally)

**Comment by WadeBarnes** [comment]
> The dependabot file does not conform to prettier formatting rules.
> 
> I'll run prettier on the file and update the PR (or you can run prettier locally)

Ok, so just a non-descript output.  I'll look into it.

**Comment by WadeBarnes** [comment]
@TimoGlastra, Give that a go.

**Comment by WadeBarnes** [comment]
Pushed Prettier formatting changes.  Should work this time.

**Comment by TimoGlastra** [comment]
Sorry for having to deal with these non important issues. Thanks for the contribution!

**Review by TimoGlastra — APPROVED** [review]

**Pull request merged**
